language: csharp
solution: ./server/SignalR.sln

matrix:
  include:
    dotnet: 2.1.302
    mono: none
    script:
    - cd server
    - dotnet restore
    - dotnet build
    - cd SignalR.Test
    - dotnet test